name = "mantenimiento"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
main = "./dist/_worker.js/index.js"
assets = { directory = "./dist/client" }

[[d1_databases]]
binding = "DB"
database_name = "mantenimiento-db"
database_id = "a4a8b34e-6b56-42b5-a393-ca5a43fcb38a"

[[r2_buckets]]
binding = "R2"
bucket_name = "mantenimiento-files"

[vars]
JWT_SECRET = "db9f323a6eb27c41b23eee4fa81077ab7a3cf826367bcb5ab19e99d9c61a8954"
BASE_URL = "https://mantenimiento.enrique0343.workers.dev"
